### ISSUE TITLE
Recent error during queries

### ISSUE THREAD

**Issue by kng229** [hiratake55/RForcecom#11]
I've been having persistent issues with RForcecom for about 2 weeks now, despite no changes to my code.  I'm simply trying:

session <- rforcecom.login(account, password, "http://na12.salesforce.com/", "30.0")
soqlQuery <- "SELECT LEADSOURCE, CREATEDDATE, COHORT__C, RECORDTYPEID FROM Lead"
v <- rforcecom.query(session, soqlQuery)

After waiting for a long time, I get the error:
Error in function(type, msg, asError = TRUE)  : 
  Failed to connect to na12.salesforce.com port 443: Timed out

It sometimes works when I query Lead, it never works anymore when I query Task.

**Comment by hiratake55** [comment]
Updated `rforcecom.login` in RForcecom 0.8.
