### ISSUE TITLE
Login failure with passwords including "&"  -- JS at fault?

### ISSUE THREAD

**Issue by jmeb** [hiratake55/RForcecom#17]
Attempted login with password including an "&" fails for the following reason:

    > session <- rforcecom.login(username, password, instanceURL, apiVersion)
     Error in rforcecom.login(username, password, instanceURL, apiVersion) : 
      The entity name must immediately follow the '&' in the entity reference.

Same syntax with a password not containing an "&"  is successful. Perhaps this is a JS/XML issue and not strictly with RForcecom.

**Comment by ReportMort** [comment]
@jmeb Certain characters need to be escaped in the XML call and "&" is one of them. The quick fix is to substitute the ampersand symbol in your password with "&amp;" and then everything should work fine. 

I'll submit a request to escape certain characters so you won't need to do that hack in the future.

**Characters to escape:**
```
'&' --> '&amp';
'<' --> '&lt';
'>' --> '&gt';
```
