### ISSUE TITLE
issue : when submitting bulk query , Error in UseMethod("xmlRoot") 

### ISSUE THREAD

**Issue by swapnilshrikhande** [hiratake55/RForcecom#33]
- When I first run the code, the package requested to install 'xml2" package which I did. 
- Able to login and get session object
- Able to get server timestamp
- But when trying to submit bulkQuery as below, viewing this issue

 `
No encoding supplied: defaulting to UTF-8.
Error in UseMethod("xmlRoot") : 
  no applicable method for 'xmlRoot' applied to an object of class "c('xml_document', 'xml_node')"`

- Bulk Query:

`
serverTimeStamp <- rforcecom.getServerTimestamp(session);
query <- "SELECT Id, Name FROM Account LIMIT 10";
job_info <- rforcecom.createBulkJob(session, operation='query', object='Account')
batch_query_info <- rforcecom.submitBulkQuery(session,
                                              jobId=job_info$id,
                                              query=query)
`

**Comment by ReportMort** [comment]
The `httr` package made some significant changes in the latest version (v1.1.0), that causes this error. I've submitted a bugfix here: https://github.com/hiratake55/RForcecom/pull/34

**Comment by swapnilshrikhande** [comment]
@ReportMort Thanks Steve. It is working great.
Tested #34 using
```
library(devtools)
install_github('ReportMort/RForcecom', ref='metadata-api');
```

**Comment by nelsonauner** [comment]
Now that ReportMort's fix has been merged into master (but not yet on CRAN), this also works and incorporates additional fixes: 

```
library(devtools)
install_github('hiratake55/RForcecom')
```
