### ISSUE TITLE
Count() in SOQL Returning Null

### ISSUE THREAD

**Issue by Btibert3** [hiratake55/RForcecom#41]
Perhaps I am missing something obvious, but I wanted to run a simple query that counts the number of Account records in my org.  I was expecting the query below to work given [this page](https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select_count.htm).

```
SOQL = "SELECT count() FROM Account"
dat = rforcecom.query(session, SOQL)
dat
```

but it returns `NULL`.  In the org that I am connected to, there are 48 records.

**Comment by ReportMort** [comment]
Hey @Btibert3, 

I'd recommend counting a specific field like this:

```
query <- "SELECT 
              COUNT(Id) cnt
          FROM Opportunity"
rforcecom.query(session, query)
```

The resulting XML returned by the API is a little more structured. `COUNT()` gives back nothing, but an attribute called totalSize that makes it hard to fit into the traditional parsing workflow.
