### ISSUE TITLE
rforcecom.query for OpportunityFieldHistory 

### ISSUE THREAD

**Issue by B2Silva** [hiratake55/RForcecom#45]
I am a newbie on R and I was using the version 0.8 of RForcecom and now I updated to version 1.1 and the following query gave me a weird result. It doesn't retrieve the NewValue and the Oldvalue.

Query:

> query_opportunityfieldhistory<-"SELECT ID,IsDeleted,OpportunityId,CreatedDate,Field, OldValue, NewValue , Opportunity.Is_New_Logo__c
>  FROM OpportunityFieldHistory WHERE  CreatedDate >=2016-09-01T00:00:00Z and Field='StageName' 
> opportunityfieldhistory_table<-rforcecom.query(session, query_opportunityfieldhistory)

With version 0.7, the colnames appeared as "NewValue.text" and "OldValue.text" and now appeared one one field with the colname like "xsd:string.text"

![image](https://cloud.githubusercontent.com/assets/11915591/18253102/02ca44fe-738a-11e6-9bf4-5dfa97b8fffb.png)

I am wondering if you can help me on this.

**Comment by GavinOB** [comment]
NewValue and OldValue are Salesforce [anyType fields](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/field_types.htm) that have the data type attached as an XML attribute. The column names are being set by the query_parser function in rforcecom.utils.R. I'm not sure how to fix this without possibly impacting multi-object queries.
