### ISSUE TITLE
How to use queryMore

### ISSUE THREAD

**Issue by samuel-pt** [hiratake55/RForcecom#49]
I am querying Salesforce objects using Rforcecom library. Recently no.of results of my query got increased to 2500.

As the Salesforce limit of a SOQL is 2000, Rforcecom.query() resulted in fetching 2000 records. Now I want to query remaining records. I've looked into queryMore documentation and found that it requires nextRecordsUrl as parameter.

How to get nextRecordsUrl? Is there a way to get it in Rforcecom?

Note: As the result will not be huge, I don't want to use BulkQuery

**Comment by ReportMort** [comment]
@samuel-pt the function `rforcecom.query` calls queryMore automatically, so you shouldn't need to use queryMore. `rforcecom.query` should pull back all the records by itself regardless of size. If not, then it is likely a bug or your recordset is smaller than you think.

**Comment by samuel-pt** [comment]
@ReportMort Just now found that my recordset is smaller than I expected. It is exactly 2000. Thanks for pointing it out

But just curious, is there a way to get nextRecordsUrl?

**Comment by ReportMort** [comment]
@samuel-pt Yes, there is a way. Check out these lines from the `rforcecom.query` function: https://github.com/hiratake55/RForcecom/blob/master/R/rforcecom.query.R#L14-L37

It's getting the XML back from Salesforce, then parsing and pulling out that specific element from the XML and if it exists, then it will run `rforcecom.queryMore` (Line 37).

**Comment by samuel-pt** [comment]
@ReportMort - Thanks for your support. We are able to query all the records using query(). Thanks for providing this wonderful library.

**Comment by rvij** [comment]
I am only getting 10 records from the Rforcecom.query() call, is there something I need to do to get more records, I am pretty sure that the query should return > 100 records? I am running this against Salesforce test environment, is there a issue with the environment?

**Comment by ReportMort** [comment]
@rvij There is no restriction on the test environment. Would you mind checking the query recordset in 3rd party tool to verify the number of rows your query should return? Use this one: https://workbench.developerforce.com

It should be easy in this tool to run a SOQL query against an object and see the records that should be returned by the SOQL.
