### ISSUE TITLE
Error in rforcecom.query()

### ISSUE THREAD

**Issue by ampu3ro** [hiratake55/RForcecom#5]
<pre>
Error in rbind(deparse.level, ...) :
 numbers of columns of arguments do not match
</pre>

Occurs when some fields are not present. Can be fixed with rbind.fill() in library(plyr)

**Comment by bduric** [comment]
Hi,
This is great and it works perfectly on most of my queries. However,I am getting QUERY_TIMEOUT error. Is it possible to tweak on my side and have this 
http://www.salesforce.com/us/developer/docs/apexcode/Content/apex_callouts_timeouts.htm
callout limit extended?

Thanks
