### ISSUE TITLE
CSV forcing in rforcecom.createBulkJob prevents attachment upload in Document object

### ISSUE THREAD

**Issue by richardjwood** [hiratake55/RForcecom#50]
The `rforcecom.createBulkJob` function sets the `contentType` to `ZIP_CSV` for the `Attachment` object, and to `CSV` for all others. However, to upload an attachment to the `Document` object, we also need to use the `ZIP_CSV` `contentType`. So far I've been working around this by making the following change:

Original code:
```
if (object == 'Attachment') {
    if (operation != 'insert') stop('only insert operations are supported for the Attachment object')
    contentType <- 'ZIP_CSV'`
} else {
    contentType <- 'CSV' # user cannot control type  `
}
```
My modification (this could probably be done more elegantly):
```
if (object == 'Attachment') {
    if (operation != 'insert') stop('only insert operations are supported for the Attachment object')
    contentType <- 'ZIP_CSV'
}
if (object == 'Document') {
    contentType <- 'ZIP_CSV'
}
if (!exists('contentType')) {
    contentType <- 'CSV' # user cannot control type  
}
```

There may be other objects affected (and I imagine custom objects as well), so adding `contentType` as an input to the function (with a default of `CSV` might be a better solution.)

**Comment by ReportMort** [comment]
@richardjwood Thanks for the heads up. I've created #52 to address the issue and give users the option to specify any of the 4 possible content types with whichever objects they'd like.
