### ISSUE TITLE
Salesforce will disable TLS 1.0 in July!!!

### ISSUE THREAD

**Issue by nicw4ves** [hiratake55/RForcecom#60]
Does this packet follow the TLS 1.1 or 1.0?
Salesforce will disable TLS 1.0 in July.
How can I make my applications follow the TLS 1.1 protocol?

Thanks!

**Comment by hiratake55** [comment]
Hi @nicw4ves 

Thank you for information!
RForcecom uses "httr" package for HTTPS connectivity and as far as I checked "httr" supports TLS 1.2. If you found something suspicious output, please feel free to let me know.

![httr](https://cloud.githubusercontent.com/assets/101812/26529529/5c78288e-43fc-11e7-9f05-65336b824577.png)
